# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\pyNMRGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pyNMRGui(object):
    def setupUi(self, pyNMRGui):
        pyNMRGui.setObjectName("pyNMRGui")
        pyNMRGui.resize(1550, 1532)
        pyNMRGui.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(pyNMRGui)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(1750, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 169, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 169, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 169, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_4.addWidget(self.label_29)
        self.lblFileName = QtWidgets.QLineEdit(self.frame_2)
        self.lblFileName.setObjectName("lblFileName")
        self.horizontalLayout_4.addWidget(self.lblFileName)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.chbClearData = QtWidgets.QCheckBox(self.frame_2)
        self.chbClearData.setObjectName("chbClearData")
        self.gridLayout.addWidget(self.chbClearData, 5, 6, 1, 1)
        self.pbPlotFIDMax = QtWidgets.QPushButton(self.frame_2)
        self.pbPlotFIDMax.setObjectName("pbPlotFIDMax")
        self.gridLayout.addWidget(self.pbPlotFIDMax, 3, 19, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 12, 1, 1)
        self.leRFTXDelay = QtWidgets.QLineEdit(self.frame_2)
        self.leRFTXDelay.setObjectName("leRFTXDelay")
        self.gridLayout.addWidget(self.leRFTXDelay, 4, 8, 1, 1)
        self.lenTD3 = QtWidgets.QLineEdit(self.frame_2)
        self.lenTD3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lenTD3.setAlignment(QtCore.Qt.AlignCenter)
        self.lenTD3.setObjectName("lenTD3")
        self.gridLayout.addWidget(self.lenTD3, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 11, 1, 1)
        self.leT180 = QtWidgets.QLineEdit(self.frame_2)
        self.leT180.setObjectName("leT180")
        self.gridLayout.addWidget(self.leT180, 4, 12, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 11, 1, 1)
        self.lbGamma = QtWidgets.QLabel(self.frame_2)
        self.lbGamma.setAlignment(QtCore.Qt.AlignCenter)
        self.lbGamma.setObjectName("lbGamma")
        self.gridLayout.addWidget(self.lbGamma, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 15, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lenPoints = QtWidgets.QLineEdit(self.frame_2)
        self.lenPoints.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lenPoints.setObjectName("lenPoints")
        self.gridLayout.addWidget(self.lenPoints, 1, 1, 1, 1)
        self.leNutationStart = QtWidgets.QLineEdit(self.frame_2)
        self.leNutationStart.setObjectName("leNutationStart")
        self.gridLayout.addWidget(self.leNutationStart, 0, 12, 1, 1)
        self.leNutationIncrement = QtWidgets.QLineEdit(self.frame_2)
        self.leNutationIncrement.setObjectName("leNutationIncrement")
        self.gridLayout.addWidget(self.leNutationIncrement, 1, 12, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 11, 1, 1)
        self.sbRepeat = QtWidgets.QSpinBox(self.frame_2)
        self.sbRepeat.setMinimum(-1)
        self.sbRepeat.setObjectName("sbRepeat")
        self.gridLayout.addWidget(self.sbRepeat, 4, 3, 1, 1)
        self.leTauCPMG = QtWidgets.QLineEdit(self.frame_2)
        self.leTauCPMG.setObjectName("leTauCPMG")
        self.gridLayout.addWidget(self.leTauCPMG, 3, 12, 1, 1)
        self.lenSpectra = QtWidgets.QLineEdit(self.frame_2)
        self.lenSpectra.setMaximumSize(QtCore.QSize(150, 16777187))
        self.lenSpectra.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lenSpectra.setAlignment(QtCore.Qt.AlignCenter)
        self.lenSpectra.setObjectName("lenSpectra")
        self.gridLayout.addWidget(self.lenSpectra, 3, 1, 1, 1)
        self.leRFCoilTaper = QtWidgets.QLineEdit(self.frame_2)
        self.leRFCoilTaper.setObjectName("leRFCoilTaper")
        self.gridLayout.addWidget(self.leRFCoilTaper, 1, 8, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 6, 1, 1)
        self.sbViewCurveN = QtWidgets.QSpinBox(self.frame_2)
        self.sbViewCurveN.setMinimum(-1)
        self.sbViewCurveN.setProperty("value", -1)
        self.sbViewCurveN.setObjectName("sbViewCurveN")
        self.gridLayout.addWidget(self.sbViewCurveN, 3, 3, 1, 1)
        self.leRFamplitude = QtWidgets.QLineEdit(self.frame_2)
        self.leRFamplitude.setObjectName("leRFamplitude")
        self.gridLayout.addWidget(self.leRFamplitude, 0, 8, 1, 1)
        self.leSample = QtWidgets.QLineEdit(self.frame_2)
        self.leSample.setObjectName("leSample")
        self.gridLayout.addWidget(self.leSample, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 11, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.leTemperature = QtWidgets.QLineEdit(self.frame_2)
        self.leTemperature.setObjectName("leTemperature")
        self.gridLayout.addWidget(self.leTemperature, 1, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 0, 1, 1)
        self.lblF0 = QtWidgets.QLabel(self.frame_2)
        self.lblF0.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblF0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblF0.setObjectName("lblF0")
        self.gridLayout.addWidget(self.lblF0, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.leField = QtWidgets.QLineEdit(self.frame_2)
        self.leField.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leField.setObjectName("leField")
        self.gridLayout.addWidget(self.leField, 0, 3, 1, 1)
        self.let90 = QtWidgets.QLineEdit(self.frame_2)
        self.let90.setObjectName("let90")
        self.gridLayout.addWidget(self.let90, 3, 8, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 1, 4, 1, 1)
        self.cbDataType = QtWidgets.QComboBox(self.frame_2)
        self.cbDataType.setObjectName("cbDataType")
        self.cbDataType.addItem("")
        self.cbDataType.addItem("")
        self.cbDataType.addItem("")
        self.cbDataType.addItem("")
        self.gridLayout.addWidget(self.cbDataType, 1, 3, 1, 1)
        self.cbPulseSequence = QtWidgets.QComboBox(self.frame_2)
        self.cbPulseSequence.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cbPulseSequence.setObjectName("cbPulseSequence")
        self.cbPulseSequence.addItem("")
        self.cbPulseSequence.addItem("")
        self.cbPulseSequence.addItem("")
        self.cbPulseSequence.addItem("")
        self.cbPulseSequence.addItem("")
        self.cbPulseSequence.addItem("")
        self.cbPulseSequence.addItem("")
        self.gridLayout.addWidget(self.cbPulseSequence, 3, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 6, 1, 1)
        self.lePhase = QtWidgets.QLineEdit(self.frame_2)
        self.lePhase.setObjectName("lePhase")
        self.gridLayout.addWidget(self.lePhase, 5, 3, 1, 1)
        self.hsPhase = QtWidgets.QSlider(self.frame_2)
        self.hsPhase.setMinimum(-1800)
        self.hsPhase.setMaximum(1800)
        self.hsPhase.setSingleStep(1)
        self.hsPhase.setSliderPosition(0)
        self.hsPhase.setOrientation(QtCore.Qt.Horizontal)
        self.hsPhase.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.hsPhase.setObjectName("hsPhase")
        self.gridLayout.addWidget(self.hsPhase, 5, 1, 1, 2)
        self.leLastDelay = QtWidgets.QLineEdit(self.frame_2)
        self.leLastDelay.setObjectName("leLastDelay")
        self.gridLayout.addWidget(self.leLastDelay, 4, 5, 1, 1)
        self.pbFindIntWidth = QtWidgets.QPushButton(self.frame_2)
        self.pbFindIntWidth.setObjectName("pbFindIntWidth")
        self.gridLayout.addWidget(self.pbFindIntWidth, 1, 20, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 0, 1, 1)
        self.lejStop = QtWidgets.QLineEdit(self.frame_2)
        self.lejStop.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lejStop.setObjectName("lejStop")
        self.gridLayout.addWidget(self.lejStop, 5, 20, 1, 1)
        self.pbIntegrate = QtWidgets.QPushButton(self.frame_2)
        self.pbIntegrate.setObjectName("pbIntegrate")
        self.gridLayout.addWidget(self.pbIntegrate, 3, 20, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 2, 1, 1)
        self.pbFFT = QtWidgets.QPushButton(self.frame_2)
        self.pbFFT.setObjectName("pbFFT")
        self.gridLayout.addWidget(self.pbFFT, 0, 20, 1, 1)
        self.lenPW50 = QtWidgets.QLineEdit(self.frame_2)
        self.lenPW50.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lenPW50.setObjectName("lenPW50")
        self.gridLayout.addWidget(self.lenPW50, 1, 19, 1, 1)
        self.lePhaseSpectra = QtWidgets.QLineEdit(self.frame_2)
        self.lePhaseSpectra.setObjectName("lePhaseSpectra")
        self.gridLayout.addWidget(self.lePhaseSpectra, 5, 5, 1, 1)
        self.pbPhase = QtWidgets.QPushButton(self.frame_2)
        self.pbPhase.setObjectName("pbPhase")
        self.gridLayout.addWidget(self.pbPhase, 5, 4, 1, 1)
        self.pbSubtractBaseLines = QtWidgets.QPushButton(self.frame_2)
        self.pbSubtractBaseLines.setObjectName("pbSubtractBaseLines")
        self.gridLayout.addWidget(self.pbSubtractBaseLines, 0, 19, 1, 1)
        self.cbGradOrientation = QtWidgets.QComboBox(self.frame_2)
        self.cbGradOrientation.setObjectName("cbGradOrientation")
        self.cbGradOrientation.addItem("")
        self.cbGradOrientation.addItem("")
        self.cbGradOrientation.addItem("")
        self.gridLayout.addWidget(self.cbGradOrientation, 0, 10, 1, 1)
        self.leGradPW = QtWidgets.QLineEdit(self.frame_2)
        self.leGradPW.setObjectName("leGradPW")
        self.gridLayout.addWidget(self.leGradPW, 4, 10, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 4, 9, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 0, 9, 1, 1)
        self.leGradCal = QtWidgets.QLineEdit(self.frame_2)
        self.leGradCal.setObjectName("leGradCal")
        self.gridLayout.addWidget(self.leGradCal, 1, 10, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 9, 1, 1)
        self.leImax = QtWidgets.QLineEdit(self.frame_2)
        self.leImax.setObjectName("leImax")
        self.gridLayout.addWidget(self.leImax, 3, 10, 1, 1)
        self.lePGSEdelta = QtWidgets.QLineEdit(self.frame_2)
        self.lePGSEdelta.setObjectName("lePGSEdelta")
        self.gridLayout.addWidget(self.lePGSEdelta, 5, 10, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 3, 9, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 5, 9, 1, 1)
        self.leiStart = QtWidgets.QLineEdit(self.frame_2)
        self.leiStart.setObjectName("leiStart")
        self.gridLayout.addWidget(self.leiStart, 5, 19, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gvReal = PlotWidget(self.frame_2)
        self.gvReal.setMinimumSize(QtCore.QSize(0, 380))
        self.gvReal.setMaximumSize(QtCore.QSize(1750, 16777215))
        self.gvReal.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.gvReal.setObjectName("gvReal")
        self.verticalLayout.addWidget(self.gvReal)
        self.gvImag = PlotWidget(self.frame_2)
        self.gvImag.setMinimumSize(QtCore.QSize(0, 380))
        self.gvImag.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.gvImag.setObjectName("gvImag")
        self.verticalLayout.addWidget(self.gvImag)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.txtMessages = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMessages.sizePolicy().hasHeightForWidth())
        self.txtMessages.setSizePolicy(sizePolicy)
        self.txtMessages.setMinimumSize(QtCore.QSize(400, 0))
        self.txtMessages.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.txtMessages.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.txtMessages.setTabStopWidth(160)
        self.txtMessages.setObjectName("txtMessages")
        self.gridLayout_4.addWidget(self.txtMessages, 0, 1, 1, 1)
        pyNMRGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pyNMRGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1550, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuMake_Data = QtWidgets.QMenu(self.menubar)
        self.menuMake_Data.setObjectName("menuMake_Data")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuUncertainty = QtWidgets.QMenu(self.menubar)
        self.menuUncertainty.setObjectName("menuUncertainty")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuDiffusion = QtWidgets.QMenu(self.menubar)
        self.menuDiffusion.setObjectName("menuDiffusion")
        pyNMRGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pyNMRGui)
        self.statusbar.setObjectName("statusbar")
        pyNMRGui.setStatusBar(self.statusbar)
        self.actionOpenDataFile = QtWidgets.QAction(pyNMRGui)
        self.actionOpenDataFile.setObjectName("actionOpenDataFile")
        self.actionGeometric_DIstortion = QtWidgets.QAction(pyNMRGui)
        self.actionGeometric_DIstortion.setObjectName("actionGeometric_DIstortion")
        self.actionT1_Anaylsis = QtWidgets.QAction(pyNMRGui)
        self.actionT1_Anaylsis.setObjectName("actionT1_Anaylsis")
        self.actionT2_Analysis = QtWidgets.QAction(pyNMRGui)
        self.actionT2_Analysis.setObjectName("actionT2_Analysis")
        self.actionProton_Density_Noise = QtWidgets.QAction(pyNMRGui)
        self.actionProton_Density_Noise.setObjectName("actionProton_Density_Noise")
        self.actionSlice_thickness = QtWidgets.QAction(pyNMRGui)
        self.actionSlice_thickness.setObjectName("actionSlice_thickness")
        self.actionLoad_phantom_properties = QtWidgets.QAction(pyNMRGui)
        self.actionLoad_phantom_properties.setObjectName("actionLoad_phantom_properties")
        self.action3dViewer = QtWidgets.QAction(pyNMRGui)
        self.action3dViewer.setObjectName("action3dViewer")
        self.actionExit = QtWidgets.QAction(pyNMRGui)
        self.actionExit.setObjectName("actionExit")
        self.actionPhantom_properties = QtWidgets.QAction(pyNMRGui)
        self.actionPhantom_properties.setObjectName("actionPhantom_properties")
        self.actionSaveData = QtWidgets.QAction(pyNMRGui)
        self.actionSaveData.setObjectName("actionSaveData")
        self.actionSave_Data = QtWidgets.QAction(pyNMRGui)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionEnter_TI_list = QtWidgets.QAction(pyNMRGui)
        self.actionEnter_TI_list.setObjectName("actionEnter_TI_list")
        self.actionPlot_B1_z = QtWidgets.QAction(pyNMRGui)
        self.actionPlot_B1_z.setObjectName("actionPlot_B1_z")
        self.actionMake_T1IR_data = QtWidgets.QAction(pyNMRGui)
        self.actionMake_T1IR_data.setObjectName("actionMake_T1IR_data")
        self.actionEnter_CPMG_list = QtWidgets.QAction(pyNMRGui)
        self.actionEnter_CPMG_list.setObjectName("actionEnter_CPMG_list")
        self.actionShowDataWindow = QtWidgets.QAction(pyNMRGui)
        self.actionShowDataWindow.setObjectName("actionShowDataWindow")
        self.actionClear_Plots = QtWidgets.QAction(pyNMRGui)
        self.actionClear_Plots.setObjectName("actionClear_Plots")
        self.actionSave_Messages = QtWidgets.QAction(pyNMRGui)
        self.actionSave_Messages.setObjectName("actionSave_Messages")
        self.actionView2d = QtWidgets.QAction(pyNMRGui)
        self.actionView2d.setObjectName("actionView2d")
        self.actionSave_Report = QtWidgets.QAction(pyNMRGui)
        self.actionSave_Report.setObjectName("actionSave_Report")
        self.actionAdd_plots_to_report = QtWidgets.QAction(pyNMRGui)
        self.actionAdd_plots_to_report.setObjectName("actionAdd_plots_to_report")
        self.actionShow_TNT_header = QtWidgets.QAction(pyNMRGui)
        self.actionShow_TNT_header.setObjectName("actionShow_TNT_header")
        self.actionUncertainty_Calculation = QtWidgets.QAction(pyNMRGui)
        self.actionUncertainty_Calculation.setObjectName("actionUncertainty_Calculation")
        self.actionClear_Report = QtWidgets.QAction(pyNMRGui)
        self.actionClear_Report.setObjectName("actionClear_Report")
        self.actionChange_Plot_Background = QtWidgets.QAction(pyNMRGui)
        self.actionChange_Plot_Background.setObjectName("actionChange_Plot_Background")
        self.actionToggle_Plot_Background = QtWidgets.QAction(pyNMRGui)
        self.actionToggle_Plot_Background.setObjectName("actionToggle_Plot_Background")
        self.actionCalculate_Baselines = QtWidgets.QAction(pyNMRGui)
        self.actionCalculate_Baselines.setObjectName("actionCalculate_Baselines")
        self.actionFit_Lorentzians = QtWidgets.QAction(pyNMRGui)
        self.actionFit_Lorentzians.setObjectName("actionFit_Lorentzians")
        self.actionDelete_current_repeat = QtWidgets.QAction(pyNMRGui)
        self.actionDelete_current_repeat.setObjectName("actionDelete_current_repeat")
        self.actionReset_data = QtWidgets.QAction(pyNMRGui)
        self.actionReset_data.setObjectName("actionReset_data")
        self.actionInvert_data = QtWidgets.QAction(pyNMRGui)
        self.actionInvert_data.setObjectName("actionInvert_data")
        self.actionPlot_RI_or_AP = QtWidgets.QAction(pyNMRGui)
        self.actionPlot_RI_or_AP.setObjectName("actionPlot_RI_or_AP")
        self.actionReset_Grad_and_bvalues = QtWidgets.QAction(pyNMRGui)
        self.actionReset_Grad_and_bvalues.setObjectName("actionReset_Grad_and_bvalues")
        self.actionInput_Gradient_current_traces = QtWidgets.QAction(pyNMRGui)
        self.actionInput_Gradient_current_traces.setObjectName("actionInput_Gradient_current_traces")
        self.actionUse_measured_b_values = QtWidgets.QAction(pyNMRGui)
        self.actionUse_measured_b_values.setObjectName("actionUse_measured_b_values")
        self.actionUse_calculated_b_values = QtWidgets.QAction(pyNMRGui)
        self.actionUse_calculated_b_values.setObjectName("actionUse_calculated_b_values")
        self.actionCalculate_Image_Widths = QtWidgets.QAction(pyNMRGui)
        self.actionCalculate_Image_Widths.setObjectName("actionCalculate_Image_Widths")
        self.actionPrint_PD_Data = QtWidgets.QAction(pyNMRGui)
        self.actionPrint_PD_Data.setObjectName("actionPrint_PD_Data")
        self.actionRemove_leading_trailing_points = QtWidgets.QAction(pyNMRGui)
        self.actionRemove_leading_trailing_points.setObjectName("actionRemove_leading_trailing_points")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpenDataFile)
        self.menuFile.addAction(self.actionSaveData)
        self.menuFile.addAction(self.actionClear_Plots)
        self.menuFile.addAction(self.actionSave_Messages)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionEnter_TI_list)
        self.menuTools.addAction(self.actionEnter_CPMG_list)
        self.menuTools.addAction(self.actionPlot_B1_z)
        self.menuTools.addAction(self.actionView2d)
        self.menuTools.addAction(self.action3dViewer)
        self.menuTools.addAction(self.actionShow_TNT_header)
        self.menuTools.addAction(self.actionChange_Plot_Background)
        self.menuTools.addAction(self.actionToggle_Plot_Background)
        self.menuMake_Data.addAction(self.actionMake_T1IR_data)
        self.menuMake_Data.addAction(self.actionShowDataWindow)
        self.menuReport.addAction(self.actionAdd_plots_to_report)
        self.menuReport.addAction(self.actionSave_Report)
        self.menuReport.addAction(self.actionClear_Report)
        self.menuUncertainty.addAction(self.actionUncertainty_Calculation)
        self.menuData.addAction(self.actionCalculate_Baselines)
        self.menuData.addAction(self.actionFit_Lorentzians)
        self.menuData.addAction(self.actionDelete_current_repeat)
        self.menuData.addAction(self.actionReset_data)
        self.menuData.addAction(self.actionInvert_data)
        self.menuData.addAction(self.actionPlot_RI_or_AP)
        self.menuData.addAction(self.actionPrint_PD_Data)
        self.menuData.addAction(self.actionRemove_leading_trailing_points)
        self.menuDiffusion.addAction(self.actionInput_Gradient_current_traces)
        self.menuDiffusion.addAction(self.actionReset_Grad_and_bvalues)
        self.menuDiffusion.addAction(self.actionUse_measured_b_values)
        self.menuDiffusion.addAction(self.actionUse_calculated_b_values)
        self.menuDiffusion.addAction(self.actionCalculate_Image_Widths)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuMake_Data.menuAction())
        self.menubar.addAction(self.menuUncertainty.menuAction())
        self.menubar.addAction(self.menuDiffusion.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())

        self.retranslateUi(pyNMRGui)
        self.actionExit.triggered.connect(pyNMRGui.close)
        QtCore.QMetaObject.connectSlotsByName(pyNMRGui)

    def retranslateUi(self, pyNMRGui):
        _translate = QtCore.QCoreApplication.translate
        pyNMRGui.setWindowTitle(_translate("pyNMRGui", "PyNMR"))
        self.label_29.setText(_translate("pyNMRGui", "NMR Data File"))
        self.chbClearData.setToolTip(_translate("pyNMRGui", "Clears plots when new data is loaded"))
        self.chbClearData.setText(_translate("pyNMRGui", "Clear Data "))
        self.pbPlotFIDMax.setText(_translate("pyNMRGui", "Plot Signal Max"))
        self.label_10.setText(_translate("pyNMRGui", "iStart, iStop"))
        self.leRFTXDelay.setText(_translate("pyNMRGui", "5.0"))
        self.lenTD3.setToolTip(_translate("pyNMRGui", "Third index in 4D data array (np, ns, nr, nu)"))
        self.lenTD3.setText(_translate("pyNMRGui", "1"))
        self.label_4.setText(_translate("pyNMRGui", "<html><head/><body><p>nutation start (µs)</p></body></html>"))
        self.leT180.setToolTip(_translate("pyNMRGui", "duration of 180 degree refocussing pulse"))
        self.label_15.setText(_translate("pyNMRGui", "<html><head/><body><p>t<span style=\" vertical-align:sub;\">180</span>(µs)</p></body></html>"))
        self.lbGamma.setText(_translate("pyNMRGui", "plot type"))
        self.label_7.setText(_translate("pyNMRGui", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("pyNMRGui", "# of points"))
        self.lenPoints.setToolTip(_translate("pyNMRGui", "First index in 4D data array (np, ns, nr, nu)"))
        self.leNutationStart.setToolTip(_translate("pyNMRGui", "Start time of nutation experiment"))
        self.leNutationStart.setText(_translate("pyNMRGui", "1"))
        self.leNutationIncrement.setText(_translate("pyNMRGui", "1"))
        self.label_13.setText(_translate("pyNMRGui", "# of repeats"))
        self.label_12.setText(_translate("pyNMRGui", "# of spectra"))
        self.label_3.setText(_translate("pyNMRGui", "<html><head/><body><p>nutation increment (µs) </p></body></html>"))
        self.sbRepeat.setToolTip(_translate("pyNMRGui", "Set which data set repeats are displayed -1=all data"))
        self.leTauCPMG.setToolTip(_translate("pyNMRGui", "CPMG delay between excitation and refocussing pulses"))
        self.leTauCPMG.setText(_translate("pyNMRGui", "1.0"))
        self.lenSpectra.setToolTip(_translate("pyNMRGui", "Second index in 4D data array (np, ns, nr, nu)"))
        self.lenSpectra.setText(_translate("pyNMRGui", "20"))
        self.leRFCoilTaper.setText(_translate("pyNMRGui", "5.5"))
        self.label_19.setText(_translate("pyNMRGui", "repeats(-1=all)"))
        self.label_8.setText(_translate("pyNMRGui", "RF Amp (µT)"))
        self.sbViewCurveN.setToolTip(_translate("pyNMRGui", "Sets which spectra are displayed -1 = all spectra"))
        self.leRFamplitude.setToolTip(_translate("pyNMRGui", "RF amplitude used to fit nutation data"))
        self.leRFamplitude.setText(_translate("pyNMRGui", "435"))
        self.label_9.setText(_translate("pyNMRGui", "RF coil taper (mm)"))
        self.label_14.setText(_translate("pyNMRGui", "<html><head/><body><p><span style=\" font-family:\'Symbol\';\">t</span><span style=\" vertical-align:sub;\">CPMG</span>(ms)</p></body></html>"))
        self.label_6.setText(_translate("pyNMRGui", "Freq (MHz)"))
        self.leTemperature.setToolTip(_translate("pyNMRGui", "sample temperature for reference, taken from file name or comment"))
        self.label_20.setText(_translate("pyNMRGui", "Sample"))
        self.lblF0.setToolTip(_translate("pyNMRGui", "Resonant frequency"))
        self.lblF0.setText(_translate("pyNMRGui", "0"))
        self.label_2.setText(_translate("pyNMRGui", "B0(T)"))
        self.let90.setToolTip(_translate("pyNMRGui", "time durations for 90 degree pulse"))
        self.label_21.setText(_translate("pyNMRGui", "Temp(C)"))
        self.cbDataType.setToolTip(_translate("pyNMRGui", "Changes horizontal axis to time, frequency, ppm or index"))
        self.cbDataType.setItemText(0, _translate("pyNMRGui", "FID (s)"))
        self.cbDataType.setItemText(1, _translate("pyNMRGui", "Spectra (index)"))
        self.cbDataType.setItemText(2, _translate("pyNMRGui", "Spectra (Hz)"))
        self.cbDataType.setItemText(3, _translate("pyNMRGui", "Spectra (ppm)"))
        self.cbPulseSequence.setItemText(0, _translate("pyNMRGui", "FID"))
        self.cbPulseSequence.setItemText(1, _translate("pyNMRGui", "IR"))
        self.cbPulseSequence.setItemText(2, _translate("pyNMRGui", "nutation"))
        self.cbPulseSequence.setItemText(3, _translate("pyNMRGui", "CPMG"))
        self.cbPulseSequence.setItemText(4, _translate("pyNMRGui", "SE"))
        self.cbPulseSequence.setItemText(5, _translate("pyNMRGui", "Diffusion"))
        self.cbPulseSequence.setItemText(6, _translate("pyNMRGui", "PD"))
        self.label_22.setText(_translate("pyNMRGui", "lastdelay(ms)"))
        self.label_16.setText(_translate("pyNMRGui", "Pulse Seq"))
        self.label_23.setText(_translate("pyNMRGui", "RFtx delay(µs)"))
        self.label_5.setText(_translate("pyNMRGui", "<html><head/><body><p>t90 (µs)</p></body></html>"))
        self.lePhase.setToolTip(_translate("pyNMRGui", "Phase(deg)"))
        self.lePhase.setText(_translate("pyNMRGui", "0.0"))
        self.hsPhase.setToolTip(_translate("pyNMRGui", "PhaseSlider"))
        self.hsPhase.setWhatsThis(_translate("pyNMRGui", "<html><head/><body><p>Phase Slider</p></body></html>"))
        self.pbFindIntWidth.setToolTip(_translate("pyNMRGui", "Calculates start/stop indicies for integration"))
        self.pbFindIntWidth.setText(_translate("pyNMRGui", "Int width"))
        self.label_18.setText(_translate("pyNMRGui", "Phase(deg)"))
        self.lejStop.setToolTip(_translate("pyNMRGui", "stop index for integration"))
        self.pbIntegrate.setToolTip(_translate("pyNMRGui", "Integrates Real Part of data and plots"))
        self.pbIntegrate.setText(_translate("pyNMRGui", "Integrate"))
        self.label_17.setText(_translate("pyNMRGui", "spectra(-1=all)"))
        self.pbFFT.setText(_translate("pyNMRGui", "FFT"))
        self.lenPW50.setToolTip(_translate("pyNMRGui", "Number FWHMs to integrate over"))
        self.lenPW50.setText(_translate("pyNMRGui", "10"))
        self.lePhaseSpectra.setToolTip(_translate("pyNMRGui", "Curve to set phase on"))
        self.lePhaseSpectra.setText(_translate("pyNMRGui", "0"))
        self.pbPhase.setText(_translate("pyNMRGui", "set phase"))
        self.pbSubtractBaseLines.setToolTip(_translate("pyNMRGui", "Subtracts background determined from last 5% of the data"))
        self.pbSubtractBaseLines.setText(_translate("pyNMRGui", "Subtract BG"))
        self.cbGradOrientation.setItemText(0, _translate("pyNMRGui", "X"))
        self.cbGradOrientation.setItemText(1, _translate("pyNMRGui", "Y"))
        self.cbGradOrientation.setItemText(2, _translate("pyNMRGui", "Z"))
        self.leGradPW.setToolTip(_translate("pyNMRGui", "Gradient Duration (ms)"))
        self.label_24.setText(_translate("pyNMRGui", "Grad(ms)"))
        self.label_27.setText(_translate("pyNMRGui", "Gradient direction"))
        self.leGradCal.setToolTip(_translate("pyNMRGui", "Current gradient calibration"))
        self.label_26.setText(_translate("pyNMRGui", "Grad cal (mT/m/A)"))
        self.lePGSEdelta.setToolTip(_translate("pyNMRGui", "Delay between gradinet and 180 RF pulse (ms)"))
        self.label_28.setText(_translate("pyNMRGui", "Imax(A)"))
        self.label_25.setText(_translate("pyNMRGui", "delta(ms)"))
        self.leiStart.setToolTip(_translate("pyNMRGui", "Start index for integration"))
        self.gvReal.setToolTip(_translate("pyNMRGui", "Plot of real part of FID or spectra"))
        self.gvImag.setToolTip(_translate("pyNMRGui", "Plot of imaginary part of FID or spectra"))
        self.txtMessages.setHtml(_translate("pyNMRGui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.menuFile.setTitle(_translate("pyNMRGui", "File"))
        self.menuTools.setTitle(_translate("pyNMRGui", "Tools"))
        self.menuMake_Data.setTitle(_translate("pyNMRGui", "MakeData"))
        self.menuReport.setTitle(_translate("pyNMRGui", "Report"))
        self.menuUncertainty.setTitle(_translate("pyNMRGui", "Uncertainty"))
        self.menuData.setTitle(_translate("pyNMRGui", "Data"))
        self.menuDiffusion.setTitle(_translate("pyNMRGui", "Diffusion"))
        self.actionOpenDataFile.setText(_translate("pyNMRGui", "Open Data File"))
        self.actionOpenDataFile.setShortcut(_translate("pyNMRGui", "Ctrl+F"))
        self.actionGeometric_DIstortion.setText(_translate("pyNMRGui", "Geometric DIstortion"))
        self.actionT1_Anaylsis.setText(_translate("pyNMRGui", "T1 Anaylsis"))
        self.actionT2_Analysis.setText(_translate("pyNMRGui", "T2 Analysis"))
        self.actionProton_Density_Noise.setText(_translate("pyNMRGui", "Proton Density/Noise"))
        self.actionSlice_thickness.setText(_translate("pyNMRGui", "Slice thickness"))
        self.actionLoad_phantom_properties.setText(_translate("pyNMRGui", "ROI properties"))
        self.action3dViewer.setText(_translate("pyNMRGui", "View3d"))
        self.actionExit.setText(_translate("pyNMRGui", "Exit"))
        self.actionPhantom_properties.setText(_translate("pyNMRGui", "Phantom properties"))
        self.actionSaveData.setText(_translate("pyNMRGui", "Save Data"))
        self.actionSave_Data.setText(_translate("pyNMRGui", "Save Data"))
        self.actionEnter_TI_list.setText(_translate("pyNMRGui", "Enter TI list"))
        self.actionPlot_B1_z.setText(_translate("pyNMRGui", "plot B1(z)"))
        self.actionMake_T1IR_data.setText(_translate("pyNMRGui", "Make T1IR data"))
        self.actionEnter_CPMG_list.setText(_translate("pyNMRGui", "Enter CPMG loop"))
        self.actionShowDataWindow.setText(_translate("pyNMRGui", "ShowDataWindow"))
        self.actionClear_Plots.setText(_translate("pyNMRGui", "Clear plots"))
        self.actionSave_Messages.setText(_translate("pyNMRGui", "Save messages"))
        self.actionView2d.setText(_translate("pyNMRGui", "View2d"))
        self.actionSave_Report.setText(_translate("pyNMRGui", "Save Report"))
        self.actionAdd_plots_to_report.setText(_translate("pyNMRGui", "Add FID/spectra plots"))
        self.actionShow_TNT_header.setText(_translate("pyNMRGui", "Show TNT header"))
        self.actionUncertainty_Calculation.setText(_translate("pyNMRGui", "Uncertainty Calculation"))
        self.actionClear_Report.setText(_translate("pyNMRGui", "Clear Report"))
        self.actionChange_Plot_Background.setText(_translate("pyNMRGui", "Change Plot Background"))
        self.actionToggle_Plot_Background.setText(_translate("pyNMRGui", "Toggle Plot Background"))
        self.actionCalculate_Baselines.setText(_translate("pyNMRGui", "Calculate Baselines"))
        self.actionFit_Lorentzians.setText(_translate("pyNMRGui", "Fit Lorentzians"))
        self.actionDelete_current_repeat.setText(_translate("pyNMRGui", "Delete current repeat"))
        self.actionReset_data.setText(_translate("pyNMRGui", "Reset data"))
        self.actionInvert_data.setText(_translate("pyNMRGui", "Invert data"))
        self.actionPlot_RI_or_AP.setText(_translate("pyNMRGui", "Plot RI or AP"))
        self.actionReset_Grad_and_bvalues.setText(_translate("pyNMRGui", "Reset Grad and bvalues"))
        self.actionInput_Gradient_current_traces.setText(_translate("pyNMRGui", "Input Gradient current traces"))
        self.actionUse_measured_b_values.setText(_translate("pyNMRGui", "Use measured b-values"))
        self.actionUse_calculated_b_values.setText(_translate("pyNMRGui", "Use calculated b-values"))
        self.actionCalculate_Image_Widths.setText(_translate("pyNMRGui", "Calculate Image Wdiths"))
        self.actionPrint_PD_Data.setText(_translate("pyNMRGui", "Print PD Data"))
        self.actionRemove_leading_trailing_points.setText(_translate("pyNMRGui", "Remove leading trailing points"))

from pyqtgraph import PlotWidget
